languague: python
notifications:
  email: false

python:
	- "2.7"
	- "3.4"
	- "3.5"
	- "3.6"

os:
	- linux
	- osx

install:
	- pip install requirements.txt
	- pip install .

script:
	- python test/run_tests.py
